# Generated by Django 6.0.2 on 2026-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('emotional', 'Emotional Well-being'), ('academic', 'Academic Success')], max_length=20)),
                ('image', models.CharField(blank=True, help_text='Path to static image or URL', max_length=500, null=True)),
                ('link', models.CharField(default='#', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.CharField(blank=True, help_text='Path to static image or URL', max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_unread', models.BooleanField(default=True)),
            ],
        ),
    ]
